
package projetobluepixel;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionListener;
import projetobluepixel.Carrinho;
import projetobluepixel.ProjetoBluePixel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Arrays;


/**
 *
 * @author Helder Felipe
 * O preco estava junto a descricao, e ao separa-lo, impossibilitava o jar 
 * de executar.
 * Contadores com Preco pulam de 4 em 4;
 * Contadores sem preco pulam de 3 em 3;
 * 
 */
public class Principal extends javax.swing.JFrame {
  
    DefaultListModel lista = new DefaultListModel();
    DefaultListModel lista2 = new DefaultListModel();
    
    /**
     * Creates new form Principal
     */
    public Principal() throws Exception {
        initComponents();
        
        setLocationRelativeTo(null);
                
        buscarProduto();
        
        ProjetoBluePixel consu = new ProjetoBluePixel();
        consu.Consumo();
                
       Carrinho car = new Carrinho();
       
       List listNomeItens = new ArrayList();
       List listFotoItens = new ArrayList();
       List listDescricaoItens = new ArrayList();
       //List listPrecoItens = new ArrayList();
   
//Salva no listNome       
        for (int i = 0; i < consu.Consumo().size(); i=i+3){                            
            listNomeItens.add(consu.Consumo().get(i));       
        }
               
//Captura dado do List e joga no array pra utilizar o metodo heapsort()
        String array[] = new String[listNomeItens.size()];
        
        for(int i = 0; i < listNomeItens.size();i++){
            array[i] = (String) listNomeItens.get(i);
        }
        
        consu.heapsort(array);

//Apresenta com heapsort no JList

        for(String k: array){
            lista.addElement(k);
        }
        
//Apresenta no JList
        //for (int i = 0; i < listNomeItens.size();i++){
            //lista.addElement(listNomeItens.get(i));        
        //}
        
        this.jList1.setModel(lista);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jScrollPane3.setViewportView(jList2);

        jLabel2.setText("Produtos");

        jLabel3.setText("Sua Lista");

        jButton2.setText("Adicionar >");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton2)))
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = jList1.getSelectedIndex();
        
        List selecionado = jList1.getSelectedValuesList();

        ProjetoBluePixel obj = new ProjetoBluePixel();

        String nome;
        String foto="";
        String descricao="";
        //String preco="";
        String dataHora = obj.getDateTime();
        
        List produto = new ArrayList();
        
        try {
            int i = 0;
            for(i = 0; i < obj.Consumo().size();i=i+3){
                String verifList = obj.Consumo().get(i).toString();
                String verif = jList1.getSelectedValue().toString();

                nome = verifList;

                if (verifList.equals(verif)){
                 
                        foto= obj.Consumo().get(i=i+1).toString();
                        descricao= obj.Consumo().get(i=i+1).toString();
                        //preco= obj.Consumo().get(i=i+1).toString();
                    
                    System.out.println("Entrou"); 
       
                    ProdutoDAO acao = new ProdutoDAO();
                    
//inserir no banco
                    acao.cadastrarProduto(nome, foto, descricao, /*preco,*/ dataHora);
                     
//                    System.out.println(nome);
//                    System.out.println(foto);
//                    System.out.println(descricao);
//                    System.out.println(preco);
//                    System.out.println(dataHora);
   
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
                
            lista2.addElement(selecionado);
            jList2.setModel(lista2);
    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    public void buscarProduto(){
        
        Connection conn = null;
        
        conn = Connect.ConnectDB();
        
        ResultSet rs = null;
        PreparedStatement pst = null;
        Statement stmt = null;
        
        String query = "SELECT nm_produto FROM produto";
        
        try {
            
            pst = conn.prepareStatement(query);
            
            rs = pst.executeQuery();
         
            while (rs.next()){
     
                String produto = rs.getString("nm_produto");
                lista2.addElement(produto);
                jList2.setModel(lista2);
                
            }
       
        }catch (Exception e) {
            System.out.println("ERROR: " + e);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
